apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: bigdata-job
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: 336107977801.dkr.ecr.us-east-1.amazonaws.com/bigdata-job:latest
  imagePullPolicy: Always  #  Ensures EKS pulls your new code
  mainApplicationFile: local:///app/job.py
  sparkVersion: "3.5.0"
  executor:
    cores: 2
    instances: 3
    memory: 4g
  driver:
    cores: 1
    memory: 2g
