#!/bin/bash
# Quick Cleanup Reference
# Run from project root: ./infrastructure/scripts/cleanup.sh [environment]

echo "=========================================="
echo "AWS Infrastructure Cleanup Quick Guide"
echo "=========================================="
echo ""
echo "USAGE:"
echo "  ./infrastructure/scripts/cleanup.sh dev      # Delete dev environment"
echo "  ./infrastructure/scripts/cleanup.sh staging  # Delete staging environment"
echo "  ./infrastructure/scripts/cleanup.sh prod     # Delete production environment"
echo ""
echo "COST IMPACT:"
echo "  Dev:     ~$100-200/month savings"
echo "  Staging: ~$200-300/month savings"
echo "  Prod:    ~$300-500/month savings"
echo ""
echo "ALTERNATIVES (Less Destructive):"
echo ""
echo "1. SCALE DOWN (Keep cluster, reduce nodes)"
echo "   aws autoscaling set-desired-capacity \\"
echo "     --auto-scaling-group-name eksctl-bigdata-eks-nodegroup-ng-* \\"
echo "     --desired-capacity 1 \\"
echo "     --region us-east-1"
echo "   Cost savings: ~$150/month"
echo ""
echo "2. STOP SPARK JOB (Keep cluster and nodes)"
echo "   kubectl delete sparkapp spark-job -n spark"
echo "   Cost savings: ~$0 (job not running, nodes idle)"
echo ""
echo "3. PAUSE NAMESPACE (All jobs stopped)"
echo "   kubectl scale deployment spark-job --replicas=0 -n spark"
echo "   Cost savings: ~$0"
echo ""
echo "RECOVERY:"
echo "  make setup ENVIRONMENT=dev"
echo ""
echo "DOCUMENTATION:"
echo "  - Full guide: docs/COST_OPTIMIZATION.md"
echo "  - Cleanup script: infrastructure/scripts/cleanup.sh"
echo ""
